name: Create and CleanUp VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Set up Azure CLI
        uses: azure/cli@v2
        with:
          azcliversion: 'latest'
          inlineScript: |
            az account show
            az storage -h
          
      - name: Check if resource group exists
        id: check_rg_exists
        run: |
          if az group show --name internTaskResourceGroup &>/dev/null; then
            echo "RG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "RG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create resource group
        if: env.RG_EXISTS == 'false'
        run: az group create --name internTaskResourceGroup --location uksouth

      - name: Check if VM exists
        id: check_vm_exists
        run: |
          if az vm show --resource-group internTaskResourceGroup --name internTaskVM &>/dev/null; then
            echo "VM_EXISTS=true" >> $GITHUB_ENV
          else
            echo "VM_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create virtual machine
        if: env.VM_EXISTS == 'false'
        run: |
          az vm create \
            --resource-group internTaskResourceGroup \
            --name internTaskVM \
            --image Ubuntu2204 \
            --size Standard_B1ls \
            --admin-username azureuser \
            --generate-ssh-keys

      - name: Wait for 5 min
        if: env.VM_EXISTS == 'false'
        run: sleep 300

      - name: Delete resource group
        if: env.RG_EXISTS == 'false' && env.VM_EXISTS == 'false'
        run: |
          az group delete --name myResourceGroup --yes --no-wait
